module.exports = [
	{provider : 'AirFire Mobile' , address : '%s@sms.airfiremobile.com'},
	{provider : 'Aio Wireless' , address : '%s@mms.aiowireless.net'},
	{provider : 'Alaska Communications' , address : '%s@msg.acsalaska.com'},
	{provider : 'Alltel (Allied Wireless)' , address : '%s@sms.alltelwireless.com'},
	{provider : 'Verizon Wireless' , address : '%s@vtext.com'},
	{provider : 'Ameritech' , address : '%s@paging.acswireless.com'},
	{provider : 'AT&T Mobility' , address : '%s@txt.att.net'},
	{provider : 'AT&T Enterprise Paging' , address : '%s@page.att.net'},
	{provider : 'BellSouth' , address : '%s@bellsouth.cl'},
	{provider : 'Boost mobile' , address : '%s@sms.myboostmobile.com'},
	{provider : 'CellCom' , address : '%s@cellcom.quiktxt.com'},
	{provider : 'Cellular South' , address : '%s@csouth1.com'},
	{provider : 'Chat Mobility' , address : '%s@mail.msgsender.com'},
	{provider : 'C Spire Wireless' , address : '%s@cspire1.com'},
	{provider : 'DTC' , address : '%s@sms.advantagecell.net'},
	{provider : 'Edge Wireless' , address : '%s@sms.edgewireless.com'},
	{provider : 'Element Mobile' , address : '%s@SMS.elementmobile.net'},
	{provider : 'I-wireless(Sprint PCS)' , address : '%s@iwirelesshometext.com'},
	{provider : 'Kajeet' , address : '%s@mobile.kajeet.net'},
	{provider : 'LongLines' , address : '%s@text.longlines.com'},
	{provider : 'MetroPCS' , address : '%s@mymetropcs.com'},
	{provider : 'Nextech' , address : '%s@sms.ntwls.net'},
	{provider : 'Page Plus Cellular (Verizon)' , address : '%s@vtext.com'},
	{provider : 'Pioneer Cellular' , address : '%s@zsend.com'},
	{provider : 'Qwest Wireless' , address : '%s@qwestmp.com'},
	{provider : 'Simple Mobile' , address : '%s@smtext.com'},
	{provider : 'Southernlinc' , address : '%s@page.southernlinc.com'},
	{provider : 'South Central Communications' , address : '%s@rinasms.com'},
	{provider : 'Sprint' , address : '%s@messaging.sprintpcs.com'},
	{provider : 'Straight Talk' , address : '%s@vtext.com'},
	{provider : 'T-Mobile' , address : '%s@tmomail.net'},
	{provider : 'Teleflip' , address : '%s@teleflip.com'},
	{provider : 'Ting' , address : '%s@message.ting.com'},
	{provider : 'Unicel' , address : '%s@utext.com'},
	{provider : 'Union Wireless' , address : '%s@union-tel.com'},
	{provider : 'US Cellular' , address : '%s@email.uscc.net'},
	{provider : 'USA Mobility' , address : '%s@usamobility.net'},
	{provider : 'Verizon Wireless' , address : '%s@vtext.com'},
	{provider : 'Viaero' , address : '%s@viaerosms.com'},
	{provider : 'Virgin Mobile' , address : '%s@vmobl.com'},
	{provider : 'Voyager Mobile' , address : '%s@text.voyagermobile.com'},
	{provider : 'West Central Wireless' , address : '%s@sms.wcc.net'},
];